### ISSUE TITLE
'SGD' object has no attribute 'get_updates'

### ISSUE THREAD

**Issue by SurendraReddy509** [z-mahmud22/Mask-RCNN_TF2.14.0#2]
i got this error . anyone  help me in that please.

Epoch 1/10
Traceback (most recent call last):
  File "/content/drive/MyDrive/Object segmentation/Testing_Mask-Rcnn/fine-tune-MaskRcnn/beagle.py", line 294, in <module>
    train(model)
  File "/content/drive/MyDrive/Object segmentation/Testing_Mask-Rcnn/fine-tune-MaskRcnn/beagle.py", line 162, in train
    model.train(dataset_train, dataset_val,
  File "/usr/local/lib/python3.10/dist-packages/mask_rcnn_tf2-1.0-py3.10.egg/mrcnn/model.py", line 2371, in train
  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training_v1.py", line 856, in fit
    return func.fit(
  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training_generator_v1.py", line 647, in fit
    return fit_generator(
  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training_generator_v1.py", line 282, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training_v1.py", line 1180, in train_on_batch
    self._make_train_function()
  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training_v1.py", line 2284, in _make_train_function
    updates = self.optimizer.get_updates(
AttributeError: 'SGD' object has no attribute 'get_updates'.

**Comment by z-mahmud22** [comment]
Which version of `keras` are you using?

**Comment by SurendraReddy509** [comment]
keras==2.14.0. this one. i copied from your repo requirements

**Comment by z-mahmud22** [comment]
It seems [line# 2170](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/blob/34d4139d793460afa360501e0d056b6ee7f46afb/mrcnn/model.py#L2170) in `model.py` is causing the issue. You can replace `optimizer = keras.optimizers.SGD(...)` with `optimizer = keras.optimizers.legacy.SGD(...)` and it should solve your error. 

Please follow this [discussion](https://github.com/matterport/Mask_RCNN/issues/2977) for further reference.

**Comment by SurendraReddy509** [comment]
its working now . Thank you very much
