### ISSUE TITLE
keras.optimizers.legacy.SGD() not working

### ISSUE THREAD

**Issue by Ambaritaa** [z-mahmud22/Mask-RCNN_TF2.14.0#8]
Traceback (most recent call last):
  File "/content/Mask-RCNN_TF2.14.0/samples/balloon/balloon.py", line 317, in <module>
    train(model)
  File "/content/Mask-RCNN_TF2.14.0/samples/balloon/balloon.py", line 149, in train
    model.train(dataset_train, dataset_val,
  File "/usr/local/lib/python3.10/dist-packages/mask_rcnn_tf2-1.0-py3.10.egg/mrcnn/model.py", line 2371, in train
  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training_v1.py", line 856, in fit
    return func.fit(
  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training_generator_v1.py", line 647, in fit
    return fit_generator(
  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training_generator_v1.py", line 282, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training_v1.py", line 1180, in train_on_batch
    self._make_train_function()
  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training_v1.py", line 2284, in _make_train_function
    updates = self.optimizer.get_updates(
AttributeError: 'SGD' object has no attribute 'get_updates'

I have changed the SGD optimizer to the legacy one, but error still presists.
optimizer = tf.keras.optimizers.legacy.SGD(lr=learning_rate, momentum=momentum, clipnorm=self.config.GRADIENT_CLIP_NORM)

**Comment by Ambaritaa** [comment]
Solved, didn't run setup.py again after modifying model.py.
